### ISSUE TITLE
Nextjs v8.0.0 support?

### ISSUE THREAD

**Issue by YuriGor** [engineerapart/nextscript#6]
Is there any plans to support nextjs 8?
https://github.com/zeit/next.js/issues/6251

**Comment by codinronan** [comment]
@YuriGor Yep definitely, I have an upcoming work item to move to Next 8 so that will necessitate bumping this library too, stay tuned!

**Comment by neverlan** [comment]
Hi, any news on supporting next8 ?

**Comment by ctrimm** [comment]
Any progress with this?

**Comment by codinronan** [comment]
Hey all, I have just released version 2.0.1 which supports Next 8 and Next 9.

Note, if you are using the experimental module/nomodule support in Next >= 9.0.3 this package is no longer needed (modern code delivered to modern browsers) but if you aren't, this package is fully compatible with Next 9!
